repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: format
    name: Format
    entry: npm run format
    types: [ts]
    language: system
    pass_filenames: false
  - id: lint
    name: Lint
    entry: npm run lint
    types: [ts]
    language: system
    pass_filenames: false
  - id: test
    name: Test
    entry: npm run test
    types: [ts]
    language: system
    pass_filenames: false
