name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

env:
  COLUMNS: 150

jobs:
  test:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v3

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            **/node_modules
            **/.eslintcache
          key: >
            ${{ hashFiles('package-lock.json') }}

      - name: install
        run: npm install

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

  deploy:
    if: "success() && github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    needs: [test]
    environment: cloudflare-workers-deploy

    steps:
      - uses: actions/checkout@v4

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.cloudflare_api_token }}
          command: publish --var GITHUB_SHA:${{ github.sha }}
